"use client";
import "./admin.css";
import { useEffect, useState } from "react";
import { getBrowserSupabase } from "@/lib/supabase-browser";
import type { Member, Project, SiteSettings } from "@/lib/types";
import { defaultSettings } from "@/lib/default-settings";

const supabase = getBrowserSupabase();
type Tab = "site" | "projects" | "members";
const blankProject: Project = { id:"", title:"", category:"Photography", year:new Date().getFullYear(), image_url:"", description:"", featured:false, sort_order:0 };
const blankMember: Member = { id:"", name:"", role:"", image_url:"", bio:"", sort_order:0 };

export default function AdminPage(){
 const [session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[tab,setTab]=useState<Tab>("site"),[message,setMessage]=useState(""),[settings,setSettings]=useState<SiteSettings>(defaultSettings),[projects,setProjects]=useState<Project[]>([]),[members,setMembers]=useState<Member[]>([]),[editingProject,setEditingProject]=useState<Project|null>(null),[editingMember,setEditingMember]=useState<Member|null>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false);if(data.session)loadAll()});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)loadAll()});return()=>l.subscription.unsubscribe()},[]);
 async function loadAll(){const [{data:s},{data:p},{data:m}]=await Promise.all([supabase.from("site_settings").select("content").eq("id","default").maybeSingle(),supabase.from("projects").select("*").order("sort_order"),supabase.from("members").select("*").order("sort_order")]);if(s?.content)setSettings({...defaultSettings,...s.content});setProjects(p||[]);setMembers(m||[])}
 async function login(email:string,password:string){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message)}
 async function saveSettings(){const {error}=await supabase.from("site_settings").upsert({id:"default",content:settings,updated_at:new Date().toISOString()});setMessage(error?error.message:"Site content saved.")}
 async function saveProject(x:Project){const payload={...x};delete (payload as any).id;const r=x.id?await supabase.from("projects").update(payload).eq("id",x.id):await supabase.from("projects").insert(payload);setMessage(r.error?r.error.message:"Project saved.");setEditingProject(null);loadAll()}
 async function saveMember(x:Member){const payload={...x};delete (payload as any).id;const r=x.id?await supabase.from("members").update(payload).eq("id",x.id):await supabase.from("members").insert(payload);setMessage(r.error?r.error.message:"Member saved.");setEditingMember(null);loadAll()}
 async function remove(table:string,id:string){if(!confirm("Delete this item?"))return;const {error}=await supabase.from(table).delete().eq("id",id);setMessage(error?error.message:"Deleted.");loadAll()}
 async function uploadImage(file:File,folder:string){const ext=file.name.split(".").pop()||"jpg",path=`${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from("yn-assets").upload(path,file,{contentType:file.type});if(error)throw error;return supabase.storage.from("yn-assets").getPublicUrl(path).data.publicUrl}
 if(loading)return <div className="admin-loading">Loading…</div>;
 if(!session)return <Login onLogin={login} message={message}/>;
 return <div className="admin-shell"><aside className="admin-sidebar"><a href="/" className="admin-brand"><strong>YN</strong><span>STUDIOS / ADMIN</span></a><nav>{[["site","Site"],["projects","Projects"],["members","Members"]].map(([k,l])=><button className={tab===k?"active":""} key={k} onClick={()=>setTab(k as Tab)}>{l}</button>)}</nav><button className="admin-logout" onClick={()=>supabase.auth.signOut()}>Sign out</button></aside><main className="admin-main"><div className="admin-top"><div><p className="admin-kicker">YN Studios</p><h1>{tab==="site"?"Site content":tab==="projects"?"Projects":"Members"}</h1></div><a href="/" target="_blank">View site</a></div>{message&&<div className="admin-message">{message}</div>}{tab==="site"&&<SiteEditor settings={settings} setSettings={setSettings} save={saveSettings} uploadImage={uploadImage}/>} {tab==="projects"&&<Collection type="projects" items={projects} editing={editingProject} setEditing={setEditingProject} blank={blankProject} save={saveProject} remove={(id:string)=>remove("projects",id)} uploadImage={uploadImage}/>} {tab==="members"&&<Collection type="members" items={members} editing={editingMember} setEditing={setEditingMember} blank={blankMember} save={saveMember} remove={(id:string)=>remove("members",id)} uploadImage={uploadImage}/>}</main></div>
}
function Login({onLogin,message}:{onLogin:(e:string,p:string)=>void;message:string}){const [e,setE]=useState(""),[p,setP]=useState("");return <main className="login-page"><div className="login-box"><p className="admin-kicker">YN Studios</p><h1>Admin</h1><p>Sign in to manage the website.</p><form onSubmit={x=>{x.preventDefault();onLogin(e,p)}}><input type="email" placeholder="Email" value={e} onChange={x=>setE(x.target.value)} required/><input type="password" placeholder="Password" value={p} onChange={x=>setP(x.target.value)} required/><button>Sign in</button></form>{message&&<small>{message}</small>}</div></main>}
function SiteEditor({settings,setSettings,save,uploadImage}:{settings:SiteSettings;setSettings:(x:SiteSettings)=>void;save:()=>void;uploadImage:(f:File,folder:string)=>Promise<string>}){const [up,setUp]=useState("");const set=(k:keyof SiteSettings,v:any)=>setSettings({...settings,[k]:v});const img=async(k:"hero_image"|"about_image",f?:File)=>{if(!f)return;setUp(k);try{set(k,await uploadImage(f,"site"))}catch(e){alert(e instanceof Error?e.message:"Upload failed")}finally{setUp("")}};return <div className="editor-stack"><EditorSection title="Home"><Field label="Headline" value={settings.hero_title} onChange={v=>set("hero_title",v)}/><Field label="Intro" value={settings.hero_intro} textarea onChange={v=>set("hero_intro",v)}/><ImageField label="Hero image" url={settings.hero_image} uploading={up==="hero_image"} onFile={f=>img("hero_image",f)} onUrl={v=>set("hero_image",v)}/><ListField label="Services" values={settings.services} onChange={v=>set("services",v)}/></EditorSection><EditorSection title="Projects"><Field label="Heading" value={settings.projects_heading} onChange={v=>set("projects_heading",v)}/><Field label="Description" value={settings.projects_intro} textarea onChange={v=>set("projects_intro",v)}/></EditorSection><EditorSection title="About"><Field label="Heading" value={settings.about_heading} onChange={v=>set("about_heading",v)}/><Field label="Body" value={settings.about_body} textarea onChange={v=>set("about_body",v)}/><ImageField label="About image" url={settings.about_image} uploading={up==="about_image"} onFile={f=>img("about_image",f)} onUrl={v=>set("about_image",v)}/><ListField label="Approach" values={settings.approach} onChange={v=>set("approach",v)}/></EditorSection><EditorSection title="Contact"><Field label="Heading" value={settings.contact_heading} onChange={v=>set("contact_heading",v)}/><Field label="Intro" value={settings.contact_intro} textarea onChange={v=>set("contact_intro",v)}/><div className="two-fields"><Field label="Email" value={settings.email} onChange={v=>set("email",v)}/><Field label="Phone" value={settings.phone} onChange={v=>set("phone",v)}/></div><div className="two-fields"><Field label="Location" value={settings.location} onChange={v=>set("location",v)}/><Field label="Instagram" value={settings.instagram} onChange={v=>set("instagram",v)}/></div></EditorSection><button className="save-btn" onClick={save}>Save site content</button></div>}
function Collection({type,items,editing,setEditing,blank,save,remove,uploadImage}:any){const project=type==="projects";const [up,setUp]=useState(false);const file=async(f?:File)=>{if(!f||!editing)return;setUp(true);try{setEditing({...editing,image_url:await uploadImage(f,type)})}catch(e){alert(e instanceof Error?e.message:"Upload failed")}finally{setUp(false)}};return <div className="collection"><div className="collection-toolbar"><p>{items.length} {project?"projects":"members"}</p><button onClick={()=>setEditing({...blank,sort_order:items.length+1})}>Add {project?"project":"member"}</button></div>{editing&&<div className="editor-card"><div className="editor-card-head"><h2>{editing.id?"Edit":"New"} {project?"project":"member"}</h2><button onClick={()=>setEditing(null)}>Close</button></div><div className="two-fields"><Field label="Name / title" value={editing.title??editing.name} onChange={v=>setEditing({...editing,...(project?{title:v}:{name:v})})}/><Field label="Category / role" value={editing.category??editing.role} onChange={v=>setEditing({...editing,...(project?{category:v}:{role:v})})}/></div>{project?<Field label="Year" type="number" value={String(editing.year)} onChange={v=>setEditing({...editing,year:Number(v)})}/>:null}<Field label={project?"Description":"Bio"} value={editing.description??editing.bio??""} textarea onChange={v=>setEditing({...editing,...(project?{description:v}:{bio:v})})}/><Field label="Sort order" type="number" value={String(editing.sort_order??0)} onChange={v=>setEditing({...editing,sort_order:Number(v)})}/><ImageField label="Image" url={editing.image_url} uploading={up} onFile={file} onUrl={v=>setEditing({...editing,image_url:v})}/>{project&&<label className="check"><input type="checkbox" checked={!!editing.featured} onChange={e=>setEditing({...editing,featured:e.target.checked})}/> Featured</label>}<div className="editor-actions"><button className="save-btn" onClick={()=>save(editing)}>Save</button><button className="danger-btn" onClick={()=>setEditing(null)}>Cancel</button></div></div>}<div className="item-list">{items.map((x:any)=><div className="item-row" key={x.id}><img src={x.image_url} alt=""/><div><strong>{x.title??x.name}</strong><span>{x.category??x.role}</span></div><div className="item-actions"><button onClick={()=>setEditing(x)}>Edit</button><button className="danger-text" onClick={()=>remove(x.id)}>Delete</button></div></div>)}</div></div>}
function EditorSection({title,children}:{title:string;children:React.ReactNode}){return <section className="editor-section"><h2>{title}</h2>{children}</section>}
function Field({label,value,onChange,textarea,type="text"}:{label:string;value:string;onChange:(v:string)=>void;textarea?:boolean;type?:string}){return <label className="admin-field"><span>{label}</span>{textarea?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)}/>}</label>}
function ListField({label,values,onChange}:{label:string;values:string[];onChange:(v:string[])=>void}){return <div className="list-field"><span>{label}</span>{values.map((v,i)=><div className="list-row" key={i}><input value={v} onChange={e=>{const n=[...values];n[i]=e.target.value;onChange(n)}}/><button type="button" onClick={()=>onChange(values.filter((_,n)=>n!==i))}>Remove</button></div>)}<button type="button" onClick={()=>onChange([...values,"New item"])}>Add item</button></div>}
function ImageField({label,url,onUrl,onFile,uploading}:{label:string;url:string;onUrl:(v:string)=>void;onFile:(f?:File)=>void;uploading:boolean}){return <div className="image-field"><div className="image-field-head"><span>{label}</span><label className="upload-label">{uploading?"Uploading…":"Upload image"}<input type="file" accept="image/*" onChange={e=>onFile(e.target.files?.[0])}/></label></div>{url&&<img src={url} alt="Preview"/>}<input value={url} onChange={e=>onUrl(e.target.value)} placeholder="Image URL"/></div>}
