"use client";
import "./admin.css";
import { useEffect, useState } from "react";
import { getBrowserSupabase } from "@/lib/supabase-browser";
import type { ClientItem, Member, Project, ServiceItem, SiteSettings } from "@/lib/types";
import { defaultSettings } from "@/lib/default-settings";
import { normalizeSettings } from "@/lib/normalize";
import { siteSections, type FieldDef } from "@/lib/site-fields";
import { safeColor } from "@/lib/color";

// Created defensively: a missing env var must show a setup message, not crash the page.
const maybeSupabase = (() => {
  try {
    return getBrowserSupabase();
  } catch {
    return null;
  }
})();
const supabase = maybeSupabase as NonNullable<typeof maybeSupabase>;
type Tab = string;
const blankProject: Project = { id:"", title:"", category:"Photography", year:new Date().getFullYear(), image_url:"", description:"", featured:false, sort_order:0 };
const blankMember: Member = { id:"", name:"", role:"", image_url:"", bio:"", sort_order:0 };

export default function AdminPage(){
 if(!maybeSupabase)return <SetupNotice/>;
 return <AdminApp/>}

function SetupNotice(){return <main className="login-page"><div className="login-box setup-box"><h1>Admin not connected</h1><p>This site is missing its Supabase connection, so the admin can&apos;t sign you in.</p><ol><li>In Vercel open your project, then <b>Settings</b>, then <b>Environment Variables</b>.</li><li>Add <code>NEXT_PUBLIC_SUPABASE_URL</code> and <code>NEXT_PUBLIC_SUPABASE_ANON_KEY</code> (Supabase, then Project Settings, then API) for Production.</li><li><b>Redeploy</b> the project. These values are baked in at build time, so a redeploy is required.</li></ol><a href="/">Back to site</a></div></main>}

function AdminApp(){
 const [menuOpen,setMenuOpen]=useState(false);
 useEffect(()=>{document.body.style.overflow=menuOpen?"hidden":"";return()=>{document.body.style.overflow=""}},[menuOpen]);
 const [session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[tab,setTab]=useState<Tab>("logo"),[message,setMessage]=useState(""),[settings,setSettings]=useState<SiteSettings>(defaultSettings),[projects,setProjects]=useState<Project[]>([]),[members,setMembers]=useState<Member[]>([]),[editingProject,setEditingProject]=useState<Project|null>(null),[editingMember,setEditingMember]=useState<Member|null>(null);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false);if(data.session)loadAll()});const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)loadAll()});return()=>l.subscription.unsubscribe()},[]);
 async function loadAll(){const [{data:s},{data:p},{data:m}]=await Promise.all([supabase.from("site_settings").select("content").eq("id","default").maybeSingle(),supabase.from("projects").select("*").order("sort_order"),supabase.from("members").select("*").order("sort_order")]);if(s?.content)setSettings(normalizeSettings(s.content as Record<string,unknown>));setProjects(p||[]);setMembers(m||[])}
 async function login(email:string,password:string){const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message)}
 async function saveSettings(){const {error}=await supabase.from("site_settings").upsert({id:"default",content:settings,updated_at:new Date().toISOString()});setMessage(error?error.message:"Site content saved.")}
 async function saveProject(x:Project){const payload={...x};delete (payload as any).id;const r=x.id?await supabase.from("projects").update(payload).eq("id",x.id):await supabase.from("projects").insert(payload);setMessage(r.error?r.error.message:"Project saved.");setEditingProject(null);loadAll()}
 async function saveMember(x:Member){const payload={...x};delete (payload as any).id;const r=x.id?await supabase.from("members").update(payload).eq("id",x.id):await supabase.from("members").insert(payload);setMessage(r.error?r.error.message:"Member saved.");setEditingMember(null);loadAll()}
 async function remove(table:string,id:string){if(!confirm("Delete this item?"))return;const {error}=await supabase.from(table).delete().eq("id",id);setMessage(error?error.message:"Deleted.");loadAll()}
 async function uploadImage(file:File,folder:string){const ext=file.name.split(".").pop()||"jpg",path=`${folder}/${crypto.randomUUID()}.${ext}`;const {error}=await supabase.storage.from("yn-assets").upload(path,file,{contentType:file.type});if(error)throw error;return supabase.storage.from("yn-assets").getPublicUrl(path).data.publicUrl}
 if(loading)return <div className="admin-loading">Loading…</div>;
 if(!session)return <Login onLogin={login} message={message}/>;
 const section=siteSections.find(x=>x.id===tab);
 const groups=(["Branding","Homepage","More"] as const).map(g=>({g,items:siteSections.filter(x=>x.group===g)}));
 const goto=(id:string)=>{setTab(id);setMessage("");setMenuOpen(false);window.scrollTo({top:0})};
 const collection=tab==="projects"?"projects":tab==="members"?"members":null;
 return <div className="admin-shell"><header className="admin-mobilebar"><a href="/" className="admin-brand compact"><strong>YN</strong><span>ADMIN</span></a><span className="mobilebar-title">{section?.title}</span><button type="button" className="menu-toggle" aria-label={menuOpen?"Close menu":"Open menu"} aria-expanded={menuOpen} aria-controls="admin-sidebar" onClick={()=>setMenuOpen(o=>!o)}><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" aria-hidden>{menuOpen?<path d="M5 5l14 14M19 5L5 19"/>:<path d="M3 7h18M3 12h18M3 17h18"/>}</svg></button></header>{menuOpen&&<div className="admin-scrim" onClick={()=>setMenuOpen(false)}/>}<aside id="admin-sidebar" className={"admin-sidebar"+(menuOpen?" open":"")}><a href="/" className="admin-brand"><strong>YN</strong><span>STUDIOS / ADMIN</span></a><nav>{groups.map(({g,items})=><div className="nav-group" key={g}><p className="nav-heading">{g}</p>{items.map(x=><button className={tab===x.id?"active":""} key={x.id} onClick={()=>goto(x.id)}>{x.title}</button>)}</div>)}</nav><div className="admin-foot"><a className="admin-viewsite" href="/" target="_blank" rel="noopener noreferrer">View site</a><button className="admin-logout" onClick={()=>supabase.auth.signOut()}>Sign out</button></div></aside><main className="admin-main"><div className="admin-top"><div><p className="admin-kicker">{section?.group}</p><h1>{section?.title}</h1>{section&&<p className="admin-about">{section.about}</p>}</div><a href="/" target="_blank">View site</a></div>{message&&<div className="admin-message">{message}</div>}{section&&<SiteEditor sectionId={section.id} settings={settings} setSettings={setSettings} save={saveSettings} uploadImage={uploadImage}/>}{collection==="projects"&&<div className="collection-block"><h2 className="block-title">All projects</h2><Collection type="projects" items={projects} editing={editingProject} setEditing={setEditingProject} blank={blankProject} save={saveProject} remove={(id:string)=>remove("projects",id)} uploadImage={uploadImage}/></div>}{collection==="members"&&<div className="collection-block"><h2 className="block-title">All team members</h2><Collection type="members" items={members} editing={editingMember} setEditing={setEditingMember} blank={blankMember} save={saveMember} remove={(id:string)=>remove("members",id)} uploadImage={uploadImage}/></div>}</main></div>
}
function Login({onLogin,message}:{onLogin:(e:string,p:string)=>void;message:string}){const [e,setE]=useState(""),[p,setP]=useState("");return <main className="login-page"><div className="login-box"><p className="admin-kicker">YN Studios</p><h1>Admin</h1><p>Sign in to manage the website.</p><form onSubmit={x=>{x.preventDefault();onLogin(e,p)}}><input type="email" placeholder="Email" value={e} onChange={x=>setE(x.target.value)} required/><input type="password" placeholder="Password" value={p} onChange={x=>setP(x.target.value)} required/><button>Sign in</button></form>{message&&<small>{message}</small>}</div></main>}
function SiteEditor({sectionId,settings,setSettings,save,uploadImage}:{sectionId:string;settings:SiteSettings;setSettings:(x:SiteSettings)=>void;save:()=>void;uploadImage:(f:File,folder:string)=>Promise<string>}){
 const [up,setUp]=useState("");
 const set=(k:keyof SiteSettings,v:any)=>setSettings({...settings,[k]:v});
 const upload=async(id:string,f:File|undefined,apply:(url:string)=>void)=>{if(!f)return;setUp(id);try{apply(await uploadImage(f,"site"))}catch(e){alert(e instanceof Error?e.message:"Upload failed")}finally{setUp("")}};
 const render=(f:FieldDef)=>{
  const k=f.key as string,v:any=settings[f.key];
  switch(f.type){
   case "text":return <Field key={k} label={f.label} value={v??""} onChange={x=>set(f.key,x)} hint={f.hint}/>;
   case "textarea":return <Field key={k} label={f.label} value={v??""} textarea onChange={x=>set(f.key,x)} hint={f.hint}/>;
   case "image":return <ImageField key={k} label={f.label} hint={f.hint} url={v??""} uploading={up===k} onFile={file=>upload(k,file,u=>set(f.key,u))} onUrl={x=>set(f.key,x)}/>;
   case "color":return <ColorField key={k} label={f.label} hint={f.hint} value={v} onChange={x=>set(f.key,x)}/>;
   case "toggle":return <label key={k} className="check toggle"><input type="checkbox" checked={!!v} onChange={e=>set(f.key,e.target.checked)}/> {f.label}</label>;
   case "list":return <ListField key={k} label={f.label} values={v||[]} onChange={x=>set(f.key,x)}/>;
   case "clients":return <ObjectList<ClientItem> key={k} label={f.label} hint={f.hint} items={v||[]} blank={{name:"",logo_url:""}} addLabel="Add brand" onChange={x=>set(f.key,x)} render={(item,patch,i)=><><Field label="Brand name" value={item.name} onChange={x=>patch({name:x})}/><ImageField label="Logo (optional)" url={item.logo_url} uploading={up===k+i} onFile={file=>upload(k+i,file,u=>patch({logo_url:u}))} onUrl={x=>patch({logo_url:x})}/></>}/>;
   case "services":return <ObjectList<ServiceItem> key={k} label={f.label} hint={f.hint} items={v||[]} blank={{title:"New service",image_url:""}} addLabel="Add service card" onChange={x=>set(f.key,x)} render={(item,patch,i)=><><Field label="Title" value={item.title} onChange={x=>patch({title:x})}/><ImageField label="Image" url={item.image_url} uploading={up===k+i} onFile={file=>upload(k+i,file,u=>patch({image_url:u}))} onUrl={x=>patch({image_url:x})}/></>}/>;
  }
 };
 const sec=siteSections.find(x=>x.id===sectionId);if(!sec)return null;return <div className="editor-stack"><section className="editor-section">{sec.fields.map(render)}</section><div className="save-bar"><button className="save-btn" onClick={save}>Save changes</button></div></div>}
function ColorField({label,value,onChange,hint}:{label:string;value:string;onChange:(v:string)=>void;hint?:string}){const safe=safeColor(value);return <div className="admin-field"><span>{label}</span><div className="color-row"><input type="color" value={safe} onChange={e=>onChange(e.target.value.toUpperCase())}/><input value={value} onChange={e=>onChange(e.target.value)} placeholder="#FEE51C"/></div>{hint&&<small className="hint">{hint}</small>}</div>}
function move<T>(items:T[],i:number,d:number){const j=i+d;if(j<0||j>=items.length)return items;const n=[...items];[n[i],n[j]]=[n[j],n[i]];return n}
function ObjectList<T extends object>({label,hint,items,blank,addLabel,onChange,render}:{label:string;hint?:string;items:T[];blank:T;addLabel:string;onChange:(v:T[])=>void;render:(item:T,patch:(p:Partial<T>)=>void,i:number)=>React.ReactNode}){return <div className="list-field"><span>{label}</span>{hint&&<small className="hint">{hint}</small>}{items.map((item,i)=><div className="editor-card" key={i}>{render(item,p=>onChange(items.map((x,n)=>n===i?{...x,...p}:x)),i)}<div className="item-tools"><button type="button" onClick={()=>onChange(move(items,i,-1))} disabled={i===0}>Move up</button><button type="button" onClick={()=>onChange(move(items,i,1))} disabled={i===items.length-1}>Move down</button><button type="button" className="danger-text" onClick={()=>onChange(items.filter((_,n)=>n!==i))}>Remove</button></div></div>)}<button type="button" onClick={()=>onChange([...items,{...blank}])}>{addLabel}</button></div>}
function Collection({type,items,editing,setEditing,blank,save,remove,uploadImage}:any){const project=type==="projects";const [up,setUp]=useState(false);const file=async(f?:File)=>{if(!f||!editing)return;setUp(true);try{setEditing({...editing,image_url:await uploadImage(f,type)})}catch(e){alert(e instanceof Error?e.message:"Upload failed")}finally{setUp(false)}};return <div className="collection"><div className="collection-toolbar"><p>{items.length} {project?"projects":"members"}</p><button onClick={()=>setEditing({...blank,sort_order:items.length+1})}>Add {project?"project":"member"}</button></div>{editing&&<div className="editor-card"><div className="editor-card-head"><h2>{editing.id?"Edit":"New"} {project?"project":"member"}</h2><button onClick={()=>setEditing(null)}>Close</button></div><div className="two-fields"><Field label="Name / title" value={editing.title??editing.name} onChange={v=>setEditing({...editing,...(project?{title:v}:{name:v})})}/><Field label="Category / role" value={editing.category??editing.role} onChange={v=>setEditing({...editing,...(project?{category:v}:{role:v})})}/></div>{project?<Field label="Year" type="number" value={String(editing.year)} onChange={v=>setEditing({...editing,year:Number(v)})}/>:null}<Field label={project?"Subtitle (e.g. Fragrance Brand)":"Bio"} value={editing.description??editing.bio??""} textarea onChange={v=>setEditing({...editing,...(project?{description:v}:{bio:v})})}/><Field label="Sort order" type="number" value={String(editing.sort_order??0)} onChange={v=>setEditing({...editing,sort_order:Number(v)})}/><ImageField label="Image" url={editing.image_url} uploading={up} onFile={file} onUrl={v=>setEditing({...editing,image_url:v})}/>{project&&<label className="check"><input type="checkbox" checked={!!editing.featured} onChange={e=>setEditing({...editing,featured:e.target.checked})}/> Featured</label>}<div className="editor-actions"><button className="save-btn" onClick={()=>save(editing)}>Save</button><button className="danger-btn" onClick={()=>setEditing(null)}>Cancel</button></div></div>}<div className="item-list">{items.map((x:any)=><div className="item-row" key={x.id}><img src={x.image_url} alt=""/><div><strong>{x.title??x.name}</strong><span>{x.category??x.role}</span></div><div className="item-actions"><button onClick={()=>setEditing(x)}>Edit</button><button className="danger-text" onClick={()=>remove(x.id)}>Delete</button></div></div>)}</div></div>}
function EditorSection({title,children}:{title:string;children:React.ReactNode}){return <section className="editor-section"><h2>{title}</h2>{children}</section>}
function Field({label,value,onChange,textarea,type="text",hint}:{label:string;value:string;onChange:(v:string)=>void;textarea?:boolean;type?:string;hint?:string}){return <label className="admin-field"><span>{label}</span>{textarea?<textarea value={value} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)}/>}{hint&&<small className="hint">{hint}</small>}</label>}
function ListField({label,values,onChange}:{label:string;values:string[];onChange:(v:string[])=>void}){return <div className="list-field"><span>{label}</span>{values.map((v,i)=><div className="list-row" key={i}><input value={v} onChange={e=>{const n=[...values];n[i]=e.target.value;onChange(n)}}/><div className="row-tools"><button type="button" onClick={()=>onChange(move(values,i,-1))} disabled={i===0}>Up</button><button type="button" onClick={()=>onChange(move(values,i,1))} disabled={i===values.length-1}>Down</button><button type="button" onClick={()=>onChange(values.filter((_,n)=>n!==i))}>Remove</button></div></div>)}<button type="button" onClick={()=>onChange([...values,"New item"])}>Add item</button></div>}
function ImageField({label,url,onUrl,onFile,uploading,hint}:{label:string;hint?:string;url:string;onUrl:(v:string)=>void;onFile:(f?:File)=>void;uploading:boolean}){return <div className="image-field"><div className="image-field-head"><span>{label}</span><label className="upload-label">{uploading?"Uploading…":"Upload image"}<input type="file" accept="image/*" onChange={e=>onFile(e.target.files?.[0])}/></label></div>{hint&&<small className="hint">{hint}</small>}{url&&<img src={url} alt="Preview"/>}<input value={url} onChange={e=>onUrl(e.target.value)} placeholder="Image URL"/></div>}
