import type { SiteSettings } from "./types";

const u = (id: string, w = 1600) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=85`;

export const defaultSettings: SiteSettings = {
  site_title: "YN Studios — Ideas Captured, Brands Built",
  site_description:
    "YN Studios is a creative studio for photography, reels, Meta ads and websites — visual storytelling and digital solutions for brands, all under one roof.",
  accent_color: "#FEE51C",
  logo_text: "YN",
  logo_sub: "STUDIOS",
  logo_image: "",

  nav_home: "Home",
  nav_projects: "Projects",
  nav_about: "About",
  nav_members: "Members",
  nav_contact: "Contact",
  header_cta_label: "Let's Work",
  mobile_menu_note: "Visuals for a brighter tomorrow",

  hero_label: "YN Studios",
  hero_cta_label: "Let's Create",
  scroll_cue_label: "Scroll to explore",
  hero_title: "Ideas\nCaptured\nBrands\nBuilt",
  hero_intro: "Photography. Reels. Meta Ads.\nWebsites. And more.",
  hero_image: u("photo-1485846234645-a62644f84728", 2200),
  hero_tags: ["Visuals", "Marketing", "Digital Products", "All under one roof"],
  show_clients: true,
  clients: ["realme", "The North Face", "zomato", "Canon", "Nike", "adidas"].map((name) => ({ name, logo_url: "" })),

  show_services: true,
  services_eyebrow: "What we do",
  services_heading: "Services",
  services_link_label: "Explore All Services",
  services_intro: "A blend of creativity and strategy to help brands grow in the digital world.",
  service_items: [
    { title: "Photography", image_url: u("photo-1516035069371-29a1b244cc32", 900) },
    { title: "Reels & Video Production", image_url: u("photo-1536440136628-849c177e76a1", 900) },
    { title: "Meta Ads & Digital Marketing", image_url: u("photo-1611162617213-7d7a39e9b1d7", 900) },
    { title: "Website Development", image_url: u("photo-1498050108023-c5249f4df085", 900) },
  ],

  show_banner: true,
  banner_text: "Not just services.\nStories that\ncreate impact.",
  banner_image: u("photo-1492619375914-88005aa9e8fb", 2200),
  banner_tags: ["Brands", "People", "Ideas", "Real results"],

  projects_eyebrow: "Featured work",
  projects_heading: "Projects",
  projects_link_label: "View All Projects",
  projects_page_heading: "All projects",
  projects_page_cta: "Start a project",

  about_eyebrow: "About us",
  about_cta_label: "More About Us",
  about_heading: "Creative minds.\nReal outcomes.",
  about_body:
    "YN Studios is a creative studio focused on visual storytelling, brand growth and digital solutions. From capturing moments to building online presence, we help ideas reach the right audience.",
  about_image: u("photo-1492691527719-9d1e07e534b4", 1800),
  about_script: "Good\nVisuals\nBetter\nBrands",

  members_eyebrow: "Meet the team",
  members_cta_label: "View Our Team",
  members_heading: "The people\nbehind YN",
  members_intro: "A group of creators, strategists and developers working together to turn ideas into impact.",

  contact_eyebrow: "Get in touch",
  contact_cta_label: "Contact Us",
  contact_heading: "Let's create\ntogether",
  contact_intro: "Have a project in mind or just want to say hi?\nWe're always open to new ideas and collaborations.",
  contact_image: u("photo-1574717024653-61fd2cf4d44d", 1800),
  contact_script: "Same Vision\nDifferent Skills\nBigger Possibilities",
  form_title: "Start a project",
  form_intro: "Tell us about your idea and we'll take it from there.",
  form_name_placeholder: "Your name",
  form_email_placeholder: "Email address",
  form_type_placeholder: "What do you need?",
  form_types: ["Photography", "Reels & Video Production", "Meta Ads & Digital Marketing", "Website Development", "Something else"],
  form_message_placeholder: "Tell us about your project",
  form_submit_label: "Send on WhatsApp",
  form_sending_label: "Opening WhatsApp…",
  form_success: "Thanks! WhatsApp is opening with your message. Just press send.",
  whatsapp_number: "",
  whatsapp_greeting: "Hi! I have an enquiry from your website.",

  copyright_text: "YN Studios. All rights reserved.",
  footer_tagline: "Visuals for\na brighter tomorrow",
  email: "hello@ynstudios.in",
  phone: "+91 98765 43210",
  location: "India",
  instagram: "@yn.studios",
  youtube: "https://youtube.com",
  linkedin: "https://linkedin.com",
};
